### PR TITLE
Map (secret variable) CONAN_PASSWORD for uploading.

### PR DESCRIPTION
**Pull request by bilke**
CONAN_PASSWORD should be a secret variable defined in a variable group linked to the pipeline:

bildschirmfoto 2018-10-16 um 21 49 26

### CODE REVIEW

**Comment by Croydon** [comment]
Is this really required? Have you tried it without? It seems odd to map an environment variable to the very same environment variable to have it available as an environment variable 🤔

**Comment by uilianries** [comment]
I dont think it's necessary. In addition, when using secret variables, we could directly include in the Travis file:

https://docs.travis-ci.com/user/environment-variables/#defining-encrypted-variables-in-travisyml

**Comment by Croydon** [comment]
This is about Azure not Travis.

**Comment by uilianries** [comment]
:man_facepalming:

**Comment by uilianries** [comment]
Okay, it looks necessary:

https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=vsts&tabs=yaml%2Cbatch#secret-variables

**Comment by bilke** [comment]
@Croydon Yep, it is about Azure and it is [necessary](
https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=vsts&tabs=yaml%2Cbatch#secret-variables) (at least if you marked the variable as secret which you do of course).

**Pull request merged**
