### PR TITLE
Add GCC 8 & Clang 6

### PR DESCRIPTION
**Pull request by Croydon**

### CODE REVIEW

**Comment by uilianries** [comment]
hi @Croydon !

We discussed about this on issue https://github.com/conan-io/conan/issues/2960.

But we have received many requests to update CI support to GCC8 and CLANG6. So I'm  considering to use the new versions.

WDYT @SSE4 @solvingj ?

**Comment by Croydon** [comment]
The discussion over there seems to be about updating configs in existing repositories.

Afaik you use the templates only for new repositories?

**Comment by uilianries** [comment]
Exactly, only for new repositories. So, I see no problem to include gcc8 and clang6.

Let's wait for more thoughts.

**Comment by SSE4** [comment]
I have no objections. the only thing I worry is limited disk space issues we're running with bintray, and adding new configurations makes situation even worse. but, I guess we well be able to manage it somehow (e.g. by setting up multiple bintray accounts? or getting additional space from bintray? or removing outdating? who knows)

**Comment by uilianries** [comment]
I think we could request more space if needed for used packages :)

Also, I'm cleaning ALL outdated packages right now. Hopefully this will remove some GBs.

**Pull request merged**
