### PR TITLE
Fix bad license path

### PR DESCRIPTION
**Pull request by uilianries**
Hi!

This PR fixes exports_sources for LICENSE.md

Also, I changed to follow [recipe-quality](http://docs.conan.io/en/latest/packaging/bintray/conan_center_guide.html#recipe-quality) recommendation.

### CODE REVIEW

**Comment by theirix** [comment]
Aren't we mixing recipe and package licences in a package? Recipe quality is not clear about it too. LICENSE.md contains a recipe license (it's from bincrafters). Upstream license is specified at `license` property of conanfile but I don't know if it is expected to be extracted at packaging time.

**Comment by theirix** [comment]
By the way, recipe quality notes:
> LICENSE of the recipe: The public repository must contain a LICENSE file with an OSS license.

Don't know if it matters.

**Comment by uilianries** [comment]
Nope.

Our LICENSE.md is copied only to *export_source*, so the package won't contain our file.

The license file copied during package stage is pointed to **sources** dir, it's not our file. However, this is a recommendation, not a rule. For many projects I found other names (i.e. COPYING), for such cases we need to change the recipe, of course.

**Comment by theirix** [comment]
Got it, thanks.
I think we should modify a copy line to
```python
self.copy("sources/license*", dst="licenses", ignore_case=True, keep_path=False)
```
to avoid copying LICENSE.md by default.

**Comment by uilianries** [comment]
The point is that we use `with tools.chdir("sources")` (line 42) to avoid rewrite os.path.joins("sources", ...) on each line.

**Comment by theirix** [comment]
You are right, missed it.

**Comment by uilianries** [comment]
Thanks!

**Comment by sigmoidal** [comment]
Why are we using export_sources for our own license? I think we should use the "exports" conanfile attribute for this. Isn't the idea to store our license along the recipe ?

**Comment by uilianries** [comment]
@sigmoidal I agree with you!

In some point we changed this but I don't remember why. Maybe we should ask on slack.

**Comment by solvingj** [comment]
This has all been reconciled in the templates. closing, thanks.

**Pull request closed without merging**
