### PR TITLE
[RFC] Provide templates as cookiecutter projects

### PR DESCRIPTION
**Pull request by madebr**
As a RFC, I've converted the default template to a cookiecutter project.
This way a new conan recipe (including readme files, test package + ci files) can be created in one command.

How to install:
```
python3 -m pip install --user cookiecutter
```

How to use (I assume you've cloned this pull request in `/tmp/conan-templates`)
```
cd /tmp
cookiecutter /tmp/conan-templates/default_cookiecutter
```

After some questions, a custom conan recipe is generated in the working directory.

### CODE REVIEW

**Comment by uilianries** [comment]
Many time ago we discussed about using generators or just providing a simple templates. We voted for using simple templates.

I see no problem adding cookie cutter, since not affecting our current templates. But also, I would like to see a test. You add a travis file executing those commands to check.

**Comment by Croydon** [comment]
As @uilianries said we already were at the point where we had generators, but eventually got away from it due to user experience and maintainability.

Your suggestions only supports the default template, but why? What is about the installer_only, and header_only templates? And soon there will be default_installer_hybrids templates 

All off them would get maintained in parallel to the plain simple copy&paste templates, plus bincrafters-conventions for updating existing recipes to new conventions. This is way too much overhead in my opinion

**Comment by Croydon** [comment]
By the way, in which repository is the original template generator?

**Comment by madebr** [comment]
I've only done the default template because I didn't know whether there would be interest.
This template is based on the cookiecutter of djange: https://github.com/pydanny/cookiecutter-django

**Comment by Croydon** [comment]
> This template is based on the cookiecutter of django: https://github.com/pydanny/cookiecutter-django

I meant our former Bincrafters templates generator we had //cc @SSE4 @uilianries

**Comment by SSE4** [comment]
former generator (the one I had) is in the git history: https://github.com/bincrafters/conan-templates/commit/e12b3f131740f82a4f9de2bb5cd53e500fb3d4f0

**Comment by Croydon** [comment]
Closing because of complexity, continuous maintenance work and new possibilities like https://github.com/bincrafters/community/issues/826

**Pull request closed without merging**
